# -*- coding: utf-8 -*-
"""AppData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPR-OmAORsyrERay-8hESCOMSgbGAJXs
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

np.random.seed(42)  # for reproducibility

# Start and length
start_date = datetime(2026, 1, 1)
days = 365

data = []

for i in range(days):
    date = start_date + timedelta(days=i)
    day_type = "Weekend" if date.weekday() >= 5 else "Weekday"

    # Temperature simulation (simple sine wave for seasonality)
    temperature = 20 + 10 * np.sin(2 * np.pi * i / 365) + np.random.normal(0, 2)

    # Cooling usage increases with temperature
    cooling = max(0, np.random.normal(2 + (temperature - 20) * 0.3, 1))

    # Heating usage decreases with temperature
    heating = max(0, np.random.normal(3 - (temperature - 20) * 0.25, 1))

    # Lighting is fairly stable
    lighting = np.random.normal(4, 0.5)

    # Kitchen varies slightly more on weekends
    kitchen = np.random.normal(2, 0.5)
    if day_type == "Weekend":
        kitchen += 1

    # Entertainment also higher on weekends
    entertainment = np.random.normal(1.5, 0.5)
    if day_type == "Weekend":
        entertainment += 1

    # Cleaning mostly on weekends
    cleaning = np.random.normal(0.5, 0.2)
    if day_type == "Weekend":
        cleaning += 0.5

    # Total energy
    total_kwh = cooling + heating + lighting + kitchen + entertainment + cleaning

    data.append([
        date,
        day_type,
        round(temperature, 1),
        round(heating, 2),
        round(cooling, 2),
        round(lighting, 2),
        round(kitchen, 2),
        round(entertainment, 2),
        round(cleaning, 2),
        round(total_kwh, 2)
    ])

columns = ["Date", "Day_Type", "Temperature", "Heating", "Cooling", "Lighting", "Kitchen", "Entertainment", "Cleaning", "Total_kWh"]

df = pd.DataFrame(data, columns=columns)

# Save as CSV
df.to_csv("household_energy_2026.csv", index=False)

print(df.head())
print(df)

#Compute weekly/monthly usage per category dynamically.

#Detect anomalies (days with unusually high usage).

#Simulate savings if user reduces usage in a category.

#Feed ML models for forecasting or pattern detection.

# Make sure Date is a datetime object
df['Date'] = pd.to_datetime(df['Date'])

from datetime import datetime, timedelta

# Last day in dataset
today = df['Date'].max()
week_start = today - timedelta(days=6)

weekly_data = df[(df['Date'] >= week_start) & (df['Date'] <= today)]

categories = ['Heating', 'Cooling', 'Lighting', 'Kitchen', 'Entertainment', 'Cleaning']

weekly_category_usage = {}
for category in categories:
    weekly_category_usage[category] = weekly_data[category].sum()

print("Weekly category usage (kWh):", weekly_category_usage)

total_weekly_kwh = sum(weekly_category_usage.values())
weekly_category_percent = {cat: (kwh / total_weekly_kwh) * 100 for cat, kwh in weekly_category_usage.items()}

print("Weekly category % contribution:", weekly_category_percent)

weekend_data = weekly_data[weekly_data['Day_Type'] == 'Weekend']
weekday_data = weekly_data[weekly_data['Day_Type'] == 'Weekday']

trend = {}
for category in categories:
    trend[category] = {
        'Weekday_Avg': weekday_data[category].mean(),
        'Weekend_Avg': weekend_data[category].mean()
    }

print("Weekday vs Weekend trends:", trend)

cooling_corr = weekly_data['Cooling'].corr(weekly_data['Temperature'])
heating_corr = weekly_data['Heating'].corr(weekly_data['Temperature'])
print("Cooling vs Temp:", cooling_corr, "Heating vs Temp:", heating_corr)

insights = [
    f"Kitchen used {weekly_category_usage['Kitchen']:.1f} kWh this week, which is {weekly_category_percent['Kitchen']:.1f}% of total energy.",
    f"Cooling usage correlates with temperature: {cooling_corr:.2f}.",
    f"Lighting usage is slightly higher on weekends ({trend['Lighting']['Weekend_Avg']:.1f} kWh/day) compared to weekdays ({trend['Lighting']['Weekday_Avg']:.1f} kWh/day)."
]
print(insights)

import pandas as pd
from datetime import datetime, timedelta

# Load dataset
df = pd.read_csv("household_energy_2026.csv")
df['Date'] = pd.to_datetime(df['Date'])

# Define categories
categories = ['Heating', 'Cooling', 'Lighting', 'Kitchen', 'Entertainment', 'Cleaning']

# Define period: last 7 days
today = df['Date'].max()  # or datetime.today()
week_start = today - timedelta(days=6)
weekly_data = df[(df['Date'] >= week_start) & (df['Date'] <= today)]

# Compute category-wise weekly totals
weekly_category_usage = {cat: weekly_data[cat].sum() for cat in categories}
total_weekly_kwh = sum(weekly_category_usage.values())

# Compute category percentage contribution
weekly_category_percent = {cat: (kwh / total_weekly_kwh) * 100 for cat, kwh in weekly_category_usage.items()}

# Weekday vs weekend trends
weekend_data = weekly_data[weekly_data['Day_Type'] == 'Weekend']
weekday_data = weekly_data[weekly_data['Day_Type'] == 'Weekday']

trend_texts = []
for cat in categories:
    weekday_avg = weekday_data[cat].mean() if not weekday_data.empty else 0
    weekend_avg = weekend_data[cat].mean() if not weekend_data.empty else 0
    trend_texts.append(f"{cat} usage is higher on weekends ({weekend_avg:.1f} kWh/day) than weekdays ({weekday_avg:.1f} kWh/day).")

# Temperature correlations (Cooling & Heating)
cooling_corr = weekly_data['Cooling'].corr(weekly_data['Temperature'])
heating_corr = weekly_data['Heating'].corr(weekly_data['Temperature'])

# Generate final insights as text
insights = []

# Category totals
for cat in categories:
    insights.append(f"{cat} used {weekly_category_usage[cat]:.1f} kWh this week, which is {weekly_category_percent[cat]:.1f}% of total energy.")

# Trends
insights.extend(trend_texts)

# Temperature insights
insights.append(f"Cooling usage correlates with temperature at {cooling_corr:.2f}.")
insights.append(f"Heating usage correlates with temperature at {heating_corr:.2f}.")

# Optional: total energy summary
insights.append(f"Total energy used this week: {total_weekly_kwh:.1f} kWh.")

# Display insights
for insight in insights:
    print("-", insight)

# dynamic script example
import pandas as pd
from datetime import datetime, timedelta
import json

# Load dataset
df = pd.read_csv("household_energy_2026.csv")
df['Date'] = pd.to_datetime(df['Date'])

categories = ['Heating', 'Cooling', 'Lighting', 'Kitchen', 'Entertainment', 'Cleaning']

# Compute last 7 days
today = df['Date'].max()
week_start = today - timedelta(days=6)
weekly_data = df[(df['Date'] >= week_start) & (df['Date'] <= today)]

# Weekly totals & percentages
weekly_category_usage = {cat: weekly_data[cat].sum() for cat in categories}
total_weekly_kwh = sum(weekly_category_usage.values())
weekly_category_percent = {cat: (kwh / total_weekly_kwh) * 100 for cat, kwh in weekly_category_usage.items()}

# Weekday vs weekend trends
weekend_data = weekly_data[weekly_data['Day_Type'] == 'Weekend']
weekday_data = weekly_data[weekly_data['Day_Type'] == 'Weekday']

insights = []

# Generate category text
for cat in categories:
    insights.append(f"{cat} used {weekly_category_usage[cat]:.1f} kWh this week, which is {weekly_category_percent[cat]:.1f}% of total energy.")

# Generate weekday/weekend trends
for cat in categories:
    weekday_avg = weekday_data[cat].mean() if not weekday_data.empty else 0
    weekend_avg = weekend_data[cat].mean() if not weekend_data.empty else 0
    insights.append(f"{cat} usage is higher on weekends ({weekend_avg:.1f} kWh/day) than weekdays ({weekday_avg:.1f} kWh/day).")

# Temperature correlations
cooling_corr = weekly_data['Cooling'].corr(weekly_data['Temperature'])
heating_corr = weekly_data['Heating'].corr(weekly_data['Temperature'])
insights.append(f"Cooling usage correlates with temperature at {cooling_corr:.2f}.")
insights.append(f"Heating usage correlates with temperature at {heating_corr:.2f}.")
insights.append(f"Total energy used this week: {total_weekly_kwh:.1f} kWh.")

# Save dynamically generated insights as JSON
with open("weekly_insights.json", "w") as f:
    json.dump(insights, f)

from google.colab import files

files.download("weekly_insights.json")

from google.colab import drive
drive.mount('/content/drive')

import json
import os
os.makedirs("/content/drive/MyDrive/EnergyAppInsights", exist_ok=True)

# Save to Drive
file_path = "/content/drive/MyDrive/EnergyAppInsights/weekly_insights.json"

with open(file_path, "w") as f:
    json.dump(insights, f)

print("Saved weekly insights to Google Drive:", file_path)